### ISSUE TITLE
Error in Colab

### ISSUE THREAD

**Issue by liushuown** [yding25/GPT-Planner#6]
All four of openai's models suffer from the following problems， how can l solve it?
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
<ipython-input-40-6b3ef46bae16> in <cell line: 3>()
      1 debug = True #@param {type:"boolean"}
      2 debug_situation_index = 0 #@param {type:"integer"}
----> 3 situation_index, situation, situation_opp, situation_object, situation_predicate, situation_action = situation_simulator(task_id, debug, debug_situation_index)
      4 
      5 '''

6 frames
/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    677         stream_error = stream and "error" in resp.data
    678         if stream_error or not 200 <= rcode < 300:
--> 679             raise self.handle_error_response(
    680                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    681             )

InvalidRequestError: The model `text-curie-001` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations

**Comment by yding25** [comment]
I replied to you in another thread and mentioned that some models of ChatGPT have been deprecated. Additionally, the method to call ChatGPT has changed. Since the project was built a few years ago, it's easy to solve this issue. You can use a new method to write the functions def llm(prompt): and def generate_predicate(situation): where they used openai.Completion.create.

I am busy for the next two days, but you can try fixing it yourself in the meantime. If you prefer, you can wait, and I will address this issue in two days.
